import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "./navBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "3_DJS NIG LTD",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased scroll-smooth bg-white text-black selection:bg-[#C89A3C] selection:text-white`} data-scroll-behavior="smooth"
    >
      <NavBar header="#home" about="#about" products="#products" contact="#contact" />
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
